apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager-vault
  namespace: {{ .Values.global.namespace }}
---
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-vault-token
  namespace: {{ .Values.global.namespace }}
  annotations:
    kubernetes.io/service-account.name: cert-manager-vault
type: kubernetes.io/service-account-token
