apiVersion: v2
name: kleidia-platform
version: 1.0.0
description: Kleidia platform infrastructure (storage, OpenBao, cert-manager)
type: application
appVersion: "1.0.0"
keywords:
  - yubikey
  - openbao
  - pki
  - cert-manager
maintainers:
  - name: Kleidia Team

dependencies:
  - name: openbao
    version: "0.19.0"
    repository: "https://openbao.github.io/openbao-helm"
    condition: openbao.enabled
